// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewZealandWalks.API.Data;

#nullable disable

namespace NewZealandWalks.API.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20240320131957_Seeding Data For Difficulties and regions")]
    partial class SeedingDataForDifficultiesandregions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewZealandWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("52ce5d3d-57f8-4de5-9824-792397e14697"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("3b9a4379-7da3-4355-ae29-6a2397e19a0b"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("8e0cbae9-c25d-4293-888b-5aa9fd4b3b61"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NewZealandWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aca28b41-818d-4e31-9a93-7d4728d26e21"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "https://unsplash.com/photos/cityscape-photo-during-daytime-hIKVSVKH7No"
                        },
                        new
                        {
                            Id = new Guid("eef803ba-b4e8-4bda-a218-b2086a309b4a"),
                            Code = "NTL",
                            Name = "Northland"
                        },
                        new
                        {
                            Id = new Guid("33ad922a-0505-4859-b76e-d43d6ca48ccf"),
                            Code = "BOP",
                            Name = "Bay of plenty"
                        },
                        new
                        {
                            Id = new Guid("19aa4a46-7e2c-4596-bde3-3268a7a6823e"),
                            Code = "WGN",
                            Name = "Wellington",
                            RegionImageUrl = "https://unsplash.com/photos/mountain-near-body-of-water-during-daytime-LZVmvKlchM0"
                        },
                        new
                        {
                            Id = new Guid("33e7f348-0d4e-41e1-801b-35f78df64c4f"),
                            Code = "NSN",
                            Name = "Nelson",
                            RegionImageUrl = "https://unsplash.com/photos/mountains-covered-with-snow-near-road-75_s8iWHKLs"
                        },
                        new
                        {
                            Id = new Guid("b7879ce9-aca7-435f-b0e9-7960f7c11d6a"),
                            Code = "STL",
                            Name = "Southland"
                        });
                });

            modelBuilder.Entity("NewZealandWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NewZealandWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("NewZealandWalks.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewZealandWalks.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
